CREATE TABLE jogo_genero (
  id_jogo INT,
  id_genero INT,
  FOREIGN KEY (id_jogo) REFERENCES jogos(id),
  FOREIGN KEY (id_genero) REFERENCES genero(id_genero)
);

INSERT INTO genero (nome_genero) VALUES
('Ação'),
('Aventura'),
('RPG'),
('FPS'),
('Plataforma'),
('Esporte'),
('Corrida'),
('Estratégia'),
('Luta'),
('Puzzle'),
('Terror'),
('Simulação'),
('Battle Royale'),
('MOBA'),
('MMORPG');

INSERT INTO jogo_genero (id_jogo, id_genero) VALUES
(1, 2),  -- The Legend of Zelda: Breath of the Wild (Aventura)
(2, 1),  -- Red Dead Redemption 2 (Ação)
(2, 2),  -- Red Dead Redemption 2 (Aventura)
(3, 3),  -- The Witcher 3: Wild Hunt (RPG)
(4, 3),  -- Cyberpunk 2077 (RPG)
(5, 1),  -- God of War (Ação)
(6, 1),  -- Elden Ring (Ação)
(6, 3),  -- Elden Ring (RPG)
(7, 12), -- Minecraft (Simulação)
(8, 13), -- Fortnite (Battle Royale)
(9, 14), -- League of Legends (MOBA)
(10, 1), -- Overwatch (Ação)
(10, 4), -- Overwatch (FPS)
(11, 3), -- Hades (RPG)
(12, 10), -- Among Us (Puzzle)
(13, 1), -- Hollow Knight (Ação)
(14, 2), -- Celeste (Aventura)
(15, 2), -- Super Mario Odyssey (Aventura)
(16, 1), -- Dark Souls III (Ação)
(17, 1), -- Grand Theft Auto V (Ação)
(18, 3), -- Persona 5 (RPG)
(19, 10), -- Resident Evil 2 (Terror)
(20, 2), -- Control (Aventura)
(21, 2), -- Death Stranding (Aventura)
(22, 1), -- DOOM Eternal (Ação)
(22, 4), -- DOOM Eternal (FPS)
(23, 1), -- Sekiro: Shadows Die Twice (Ação)
(24, 3), -- Final Fantasy VII Remake (RPG)
(25, 14), -- Genshin Impact (MMORPG)
(26, 1), -- Spider-Man: Miles Morales (Ação)
(27, 1), -- Ratchet & Clank: Rift Apart (Ação)
(28, 9), -- It Takes Two (Puzzle)
(29, 2), -- Assassin’s Creed Valhalla (Aventura)
(30, 1), -- Valorant (Ação)
(30, 4), -- Valorant (FPS)
(31, 14), -- Dota 2 (MOBA)
(32, 13), -- Apex Legends (Battle Royale)
(33, 3), -- Monster Hunter: World (RPG)
(34, 2), -- The Outer Worlds (Aventura)
(35, 2), -- Star Wars Jedi: Fallen Order (Aventura)
(36, 1), -- Dead Cells (Ação)
(37, 3), -- Divinity: Original Sin 2 (RPG)
(38, 10), -- Slay the Spire (Puzzle)
(39, 2), -- Subnautica (Aventura)
(40, 2), -- The Stanley Parable (Aventura)
(41, 9), -- Baba Is You (Puzzle)
(42, 3), -- NieR: Automata (RPG)
(43, 2), -- Ori and the Will of the Wisps (Aventura)
(44, 2), -- Ghost of Tsushima (Aventura)
(45, 3), -- Disco Elysium (RPG)
(46, 2), -- Metro Exodus (Aventura)
(46, 4), -- Metro Exodus (FPS)
(47, 2), -- Horizon Zero Dawn (Aventura)
(48, 2), -- Days Gone (Aventura)
(48, 1), -- Days Gone (Ação)
(49, 1), -- Bloodborne (Ação)
(50, 1), -- Titanfall 2 (Ação)
(50, 4), -- Titanfall 2 (FPS)
(51, 2), -- The Last Guardian (Aventura)
(52, 2), -- Journey (Aventura)
(53, 1), -- The Last of Us Part II (Ação)
(53, 2), -- The Last of Us Part II (Aventura)
(53, 10), -- The Last of Us Part II (Terror)
(54, 1), -- Cyber Shadow (Ação)
(55, 12), -- Frostpunk (Simulação)
(56, 6), -- FIFA 21 (Esporte)
(57, 6), -- Madden NFL 21 (Esporte)
(58, 6), -- NBA 2K21 (Esporte)
(59, 9), -- Mortal Kombat 11 (Luta)
(60, 9), -- Street Fighter V (Luta)
(61, 9), -- Tekken 7 (Luta)
(62, 9), -- Guilty Gear Strive (Luta)
(63, 7), -- Forza Horizon 4 (Corrida)
(64, 7), -- Gran Turismo Sport (Corrida)
(65, 2), -- Crash Bandicoot 4: It’s About Time (Aventura)
(66, 6), -- Tony Hawk’s Pro Skater 1 + 2 (Esporte)
(67, 2), -- Hitman 3 (Aventura)
(68, 1), -- Cuphead (Ação)
(68, 9), -- Cuphead (Luta)
(69, 2), -- Little Nightmares II (Aventura)
(70, 10), -- Inside (Puzzle)
(71, 10), -- Limbo (Puzzle)
(72, 2), -- Ori and the Blind Forest (Aventura)
(73, 13), -- Fall Guys (Battle Royale)
(74, 12), -- No Man’s Sky (Simulação)
(75, 12), -- Factorio (Simulação)
(76, 12), -- Terraria (Simulação)
(77, 12), -- Stardew Valley (Simulação)
(78, 12), -- Don’t Starve (Simulação)
(79, 6), -- F1 2021 (Esporte)
(80, 12), -- The Sims 4 (Simulação)
(81, 12), -- Animal Crossing: New Horizons (Simulação)
(82, 3), -- Fire Emblem: Three Houses (RPG)
(83, 8), -- XCOM 2 (Estratégia)
(84, 8), -- Civilization VI (Estratégia)
(85, 8), -- Total War: Three Kingdoms (Estratégia)
(86, 8), -- Age of Empires II: Definitive Edition (Estratégia)
(87, 1), -- Halo Infinite (Ação)
(87, 4), -- Halo Infinite (FPS)
(88, 1), -- Destiny 2 (Ação)
(88, 4), -- Destiny 2 (FPS)
(89, 1), -- Borderlands 3 (Ação)
(89, 4), -- Borderlands 3 (FPS)
(90, 2), -- Far Cry 5 (Aventura)
(90, 4), -- Far Cry 5 (FPS)
(91, 4), -- Rainbow Six Siege (FPS)
(92, 10), -- Tetris Effect (Puzzle)
(93, 2), -- Returnal (Aventura)
(94, 3), -- Xenoblade Chronicles 2 (RPG)
(95, 2), -- The Legend of Zelda: Link’s Awakening (Aventura)
(96, 9), -- Super Smash Bros. Ultimate (Luta)
(97, 6), -- Splatoon 2 (Esporte)
(98, 7), -- Mario Kart 8 Deluxe (Corrida)
(99, 1), -- Bayonetta 2 (Ação)
(100, 2); -- Pikmin 3 Deluxe (Aventura)

select * from jogo_genero;