# inserindo jogo_plataforma:

CREATE TABLE jogo_plataforma (
  id_jogo INT,
  id_plataforma INT,
  FOREIGN KEY (id_jogo) REFERENCES jogos(id),
  FOREIGN KEY (id_plataforma) REFERENCES plataforma(id_plataforma)
);

INSERT INTO plataforma (nome_plataforma) VALUES
('PC'),
('PlayStation 4'),
('PlayStation 5'),
('Xbox One'),
('Xbox Series X'),
('Nintendo Switch'),
('Mobile'),
('Stadia'),
('Mac');

INSERT INTO jogo_plataforma (id_jogo, id_plataforma) VALUES
(1, 6),  -- The Legend of Zelda: Breath of the Wild (Nintendo Switch)
(2, 2),  -- Red Dead Redemption 2 (PlayStation 4)
(2, 4),  -- Red Dead Redemption 2 (Xbox One)
(2, 1),  -- Red Dead Redemption 2 (PC)
(3, 1),  -- The Witcher 3: Wild Hunt (PC)
(3, 2),  -- The Witcher 3: Wild Hunt (PlayStation 4)
(3, 4),  -- The Witcher 3: Wild Hunt (Xbox One)
(3, 6),  -- The Witcher 3: Wild Hunt (Nintendo Switch)
(4, 1),  -- Cyberpunk 2077 (PC)
(4, 2),  -- Cyberpunk 2077 (PlayStation 4)
(4, 4),  -- Cyberpunk 2077 (Xbox One)
(4, 5),  -- Cyberpunk 2077 (Xbox Series X)
(5, 2),  -- God of War (PlayStation 4)
(6, 1),  -- Elden Ring (PC)
(6, 2),  -- Elden Ring (PlayStation 4)
(6, 3),  -- Elden Ring (PlayStation 5)
(6, 4),  -- Elden Ring (Xbox One)
(6, 5),  -- Elden Ring (Xbox Series X)
(7, 1),  -- Minecraft (PC)
(7, 6),  -- Minecraft (Nintendo Switch)
(7, 7),  -- Minecraft (Mobile)
(8, 1),  -- Fortnite (PC)
(8, 6),  -- Fortnite (Nintendo Switch)
(8, 7),  -- Fortnite (Mobile)
(8, 2),  -- Fortnite (PlayStation 4)
(8, 4),  -- Fortnite (Xbox One)
(9, 1),  -- League of Legends (PC)
(10, 1), -- Overwatch (PC)
(10, 2), -- Overwatch (PlayStation 4)
(10, 4), -- Overwatch (Xbox One)
(11, 1), -- Hades (PC)
(11, 6), -- Hades (Nintendo Switch)
(12, 1), -- Among Us (PC)
(12, 7), -- Among Us (Mobile)
(13, 1), -- Hollow Knight (PC)
(13, 6), -- Hollow Knight (Nintendo Switch)
(14, 1), -- Celeste (PC)
(14, 6), -- Celeste (Nintendo Switch)
(15, 6), -- Super Mario Odyssey (Nintendo Switch)
(16, 1), -- Dark Souls III (PC)
(16, 2), -- Dark Souls III (PlayStation 4)
(16, 4), -- Dark Souls III (Xbox One)
(17, 1), -- Grand Theft Auto V (PC)
(17, 2), -- Grand Theft Auto V (PlayStation 4)
(17, 4), -- Grand Theft Auto V (Xbox One)
(18, 2), -- Persona 5 (PlayStation 4)
(19, 1), -- Resident Evil 2 (PC)
(19, 2), -- Resident Evil 2 (PlayStation 4)
(19, 4), -- Resident Evil 2 (Xbox One)
(20, 1), -- Control (PC)
(20, 2), -- Control (PlayStation 4)
(20, 4), -- Control (Xbox One)
(21, 1), -- Death Stranding (PC)
(21, 2), -- Death Stranding (PlayStation 4)
(21, 3), -- Death Stranding (PlayStation 5)
(22, 1), -- DOOM Eternal (PC)
(22, 2), -- DOOM Eternal (PlayStation 4)
(22, 4), -- DOOM Eternal (Xbox One)
(22, 6), -- DOOM Eternal (Nintendo Switch)
(23, 1), -- Sekiro: Shadows Die Twice (PC)
(23, 2), -- Sekiro: Shadows Die Twice (PlayStation 4)
(23, 4), -- Sekiro: Shadows Die Twice (Xbox One)
(24, 2), -- Final Fantasy VII Remake (PlayStation 4)
(25, 1), -- Genshin Impact (PC)
(25, 6), -- Genshin Impact (Nintendo Switch)
(25, 7), -- Genshin Impact (Mobile)
(26, 3), -- Spider-Man: Miles Morales (PlayStation 5)
(26, 2), -- Spider-Man: Miles Morales (PlayStation 4)
(27, 3), -- Ratchet & Clank: Rift Apart (PlayStation 5)
(28, 1), -- It Takes Two (PC)
(28, 2), -- It Takes Two (PlayStation 4)
(28, 4), -- It Takes Two (Xbox One)
(28, 5), -- It Takes Two (Xbox Series X)
(29, 1), -- Assassin’s Creed Valhalla (PC)
(29, 2), -- Assassin’s Creed Valhalla (PlayStation 4)
(29, 3), -- Assassin’s Creed Valhalla (PlayStation 5)
(29, 4), -- Assassin’s Creed Valhalla (Xbox One)
(29, 5), -- Assassin’s Creed Valhalla (Xbox Series X)
(30, 1), -- Valorant (PC)
(31, 1), -- Dota 2 (PC)
(32, 1), -- Apex Legends (PC)
(32, 6), -- Apex Legends (Nintendo Switch)
(32, 2), -- Apex Legends (PlayStation 4)
(32, 4), -- Apex Legends (Xbox One)
(33, 1), -- Monster Hunter: World (PC)
(33, 2), -- Monster Hunter: World (PlayStation 4)
(33, 4), -- Monster Hunter: World (Xbox One)
(34, 1), -- The Outer Worlds (PC)
(34, 2), -- The Outer Worlds (PlayStation 4)
(34, 4), -- The Outer Worlds (Xbox One)
(35, 1), -- Star Wars Jedi: Fallen Order (PC)
(35, 2), -- Star Wars Jedi: Fallen Order (PlayStation 4)
(35, 4), -- Star Wars Jedi: Fallen Order (Xbox One)
(36, 1), -- Dead Cells (PC)
(36, 6), -- Dead Cells (Nintendo Switch)
(37, 1), -- Divinity: Original Sin 2 (PC)
(37, 2), -- Divinity: Original Sin 2 (PlayStation 4)
(37, 4), -- Divinity: Original Sin 2 (Xbox One)
(38, 1), -- Slay the Spire (PC)
(38, 6), -- Slay the Spire (Nintendo Switch)
(39, 1), -- Subnautica (PC)
(39, 6), -- Subnautica (Nintendo Switch)
(40, 1), -- The Stanley Parable (PC)
(41, 1), -- Baba Is You (PC)
(41, 6), -- Baba Is You (Nintendo Switch)
(42, 1), -- NieR: Automata (PC)
(42, 2), -- NieR: Automata (PlayStation 4)
(42, 4), -- NieR: Automata (Xbox One)
(43, 1), -- Ori and the Will of the Wisps (PC)
(43, 6), -- Ori and the Will of the Wisps (Nintendo Switch)
(44, 1), -- Ghost of Tsushima (PC)
(44, 2), -- Ghost of Tsushima (PlayStation 4)
(45, 1), -- Disco Elysium (PC)
(46, 1), -- Metro Exodus (PC)
(46, 2), -- Metro Exodus (PlayStation 4)
(46, 4), -- Metro Exodus (Xbox One)
(47, 1), -- Horizon Zero Dawn (PC)
(47, 2), -- Horizon Zero Dawn (PlayStation 4)
(48, 2), -- Days Gone (PlayStation 4)
(49, 2), -- Bloodborne (PlayStation 4)
(50, 1), -- Titanfall 2 (PC)
(50, 2), -- Titanfall 2 (PlayStation 4)
(50, 4), -- Titanfall 2 (Xbox One)
(51, 2), -- The Last Guardian (PlayStation 4)
(52, 2), -- Journey (PlayStation 4)
(53, 2), -- The Last of Us Part II (PlayStation 4)
(54, 1), -- Cyber Shadow (PC)
(55, 1), -- Frostpunk (PC)
(56, 1), -- FIFA 21 (PC)
(56, 2), -- FIFA 21 (PlayStation 4)
(56, 4), -- FIFA 21 (Xbox One)
(57, 1), -- Madden NFL 21 (PC)
(58, 1), -- NBA 2K21 (PC)
(59, 1), -- Mortal Kombat 11 (PC)
(60, 2), -- Street Fighter V (PlayStation 4)
(61, 2), -- Tekken 7 (PlayStation 4)
(62, 1), -- Guilty Gear Strive (PC)
(63, 4), -- Forza Horizon 4 (Xbox One)
(64, 4), -- Gran Turismo Sport (Xbox One)
(65, 6), -- Crash Bandicoot 4: It’s About Time (Nintendo Switch)
(66, 6), -- Tony Hawk’s Pro Skater 1 + 2 (Nintendo Switch)
(67, 1), -- Hitman 3 (PC)
(68, 1), -- Cuphead (PC)
(69, 6), -- Little Nightmares II (Nintendo Switch)
(70, 1), -- Inside (PC)
(71, 1), -- Limbo (PC)
(72, 6), -- Ori and the Blind Forest (Nintendo Switch)
(73, 1), -- Fall Guys (PC)
(74, 1), -- No Man’s Sky (PC)
(75, 1), -- Factorio (PC)
(76, 1), -- Terraria (PC)
(77, 1), -- Stardew Valley (PC)
(78, 1), -- Don’t Starve (PC)
(79, 1), -- F1 2021 (PC)
(80, 1), -- The Sims 4 (PC)
(81, 1), -- Animal Crossing: New Horizons (Nintendo Switch)
(82, 2), -- Fire Emblem: Three Houses (Nintendo Switch)
(83, 1), -- XCOM 2 (PC)
(84, 1), -- Civilization VI (PC)
(85, 1), -- Total War: Three Kingdoms (PC)
(86, 1), -- Age of Empires II: Definitive Edition (PC)
(87, 1), -- Halo Infinite (PC)
(88, 1), -- Destiny 2 (PC)
(89, 1), -- Borderlands 3 (PC)
(90, 1), -- Far Cry 5 (PC)
(91, 1), -- Rainbow Six Siege (PC)
(92, 1), -- Tetris Effect (PC)
(93, 1), -- Returnal (PC)
(94, 1), -- Xenoblade Chronicles 2 (PC)
(95, 1), -- The Legend of Zelda: Link’s Awakening (PC)
(96, 1), -- Super Smash Bros. Ultimate (PC)
(97, 1), -- Splatoon 2 (PC)
(98, 1), -- Mario Kart 8 Deluxe (PC)
(99, 1), -- Bayonetta 2 (PC)
(100, 1); -- Pikmin 3 Deluxe (PC)

select * from jogo_plataforma;